name: Release Bot

on:
  push:
    tags:
      - 'v*' 

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
        contents: write
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.0.0'

    - name: Install dependencies
      run: npm install

    - name: Create zip file
      run: zip -r olminu-bot-${{ github.ref_name }}.zip . -x '*.git*' 

    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: olminu-bot-${{ github.ref_name }}.zip
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          ### Olminu Bot
          This release contains:
          - All source code.
          - Dependencies specified in `package.json`.
          - A ready-to-use ZIP file for deployment.
